### ISSUE TITLE
searx.engines.duckduckgo: Searx is blocked

### ISSUE THREAD

**Issue by y0nei** [searxng/searxng-docker#125]
```
searxng        | 2023-02-07 20:20:29,268 ERROR:searx.engines.wikidata: engine timeout
searxng        | 2023-02-07 20:20:29,356 WARNING:searx.engines.wikidata: ErrorContext('searx/search/processors/abstract.py', 102, 'count_error(self.engine_name, exception_or_message)', None, 'timeout', ()) False
searxng        | 2023-02-07 23:53:33,165 ERROR:searx.engines.wikidata: engine timeout
searxng        | 2023-02-07 23:53:33,328 WARNING:searx.engines.wikidata: ErrorContext('searx/search/processors/abstract.py', 102, 'count_error(self.engine_name, exception_or_message)', None, 'timeout', ()) False
searxng        | 2023-02-08 11:13:13,795 WARNING:searx.engines.duckduckgo: ErrorContext('searx/search/processors/online.py', 113, "response = req(params['url'], **request_args)", 'searx.exceptions.SearxEngineAccessDeniedException', None, ('HTTP error 403',)) False
searxng        | 2023-02-08 11:13:13,795 ERROR:searx.engines.duckduckgo: Searx is blocked
searxng        | Traceback (most recent call last):
searxng        |   File "/usr/local/searxng/searx/search/processors/online.py", line 160, in search
searxng        |     search_results = self._search_basic(query, params)
searxng        |   File "/usr/local/searxng/searx/search/processors/online.py", line 144, in _search_basic
searxng        |     response = self._send_http_request(params)
searxng        |   File "/usr/local/searxng/searx/search/processors/online.py", line 113, in _send_http_request
searxng        |     response = req(params['url'], **request_args)
searxng        |   File "/usr/local/searxng/searx/network/__init__.py", line 179, in post
searxng        |     return request('post', url, data=data, **kwargs)
searxng        |   File "/usr/local/searxng/searx/network/__init__.py", line 96, in request
searxng        |     return future.result(timeout)
searxng        |   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
searxng        |     return self.__get_result()
searxng        |   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
searxng        |     raise self._exception
searxng        |   File "/usr/local/searxng/searx/network/network.py", line 291, in request
searxng        |     return await self.call_client(False, method, url, **kwargs)
searxng        |   File "/usr/local/searxng/searx/network/network.py", line 274, in call_client
searxng        |     return Network.patch_response(response, do_raise_for_httperror)
searxng        |   File "/usr/local/searxng/searx/network/network.py", line 247, in patch_response
searxng        |     raise_for_httperror(response)
searxng        |   File "/usr/local/searxng/searx/network/raise_for_httperror.py", line 75, in raise_for_httperror
searxng        |     raise SearxEngineAccessDeniedException(
searxng        | searx.exceptions.SearxEngineAccessDeniedException: HTTP error 403, suspended_time=86400

```

**Comment by return42** [comment]
This is searxng-docker, your issue is related to searxng .. please use the stats page on your engine e.g. https://search.example.org/stats?engine=duckduckgo to open an issue at searxng.  

Before you open an issue please update your instance and check if this issue is already reported .. we have so many duplicates: 

- https://github.com/searxng/searxng/issues?q=is%3Aissue+%22Bug%3A+duckduckgo+engine%22
