### ISSUE TITLE
Why the same error is reported, one can access it and the other can't.

### ISSUE THREAD

**Issue by xiqoqi** [searxng/searxng-docker#126]
At first, I modified the .env and settings.yml files correctly and deleted the Caddy-related configuration in docker-compose.yaml because I used Nginx.
At this point, the docker-compose.yaml content is as follows
```
version: '3.7'

services:

  redis:
    container_name: redis
    image: "redis:alpine"
    command: redis-server --save "" --appendonly "no"
    networks:
      - searxng
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    networks:
      - searxng
    ports:
     - "127.0.0.1:52134:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
networks:
  searxng:
    ipam:
      driver: default

volumes:
  caddy-data:
  caddy-config:

```
Then run `docker-compose up`，The logs in the container are as follows
```
[root@VM-4-11-centos searxng-docker]# sudo docker-compose up
[+] Running 2/0
 ⠿ Container redis    Created                                                                                                                                                                                 0.0s
 ⠿ Container searxng  Created                                                                                                                                                                                 0.0s
Attaching to redis, searxng
redis    | 1:C 08 Feb 2023 21:11:40.620 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis    | 1:C 08 Feb 2023 21:11:40.620 # Redis version=7.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
redis    | 1:C 08 Feb 2023 21:11:40.620 # Configuration loaded
redis    | 1:M 08 Feb 2023 21:11:40.621 * monotonic clock: POSIX clock_gettime
redis    | 1:M 08 Feb 2023 21:11:40.622 * Running mode=standalone, port=6379.
redis    | 1:M 08 Feb 2023 21:11:40.622 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis    | 1:M 08 Feb 2023 21:11:40.622 # Server initialized
redis    | 1:M 08 Feb 2023 21:11:40.622 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis    | 1:M 08 Feb 2023 21:11:40.622 * Ready to accept connections
searxng  | SearXNG version 2023.2.4+7320b0c7
searxng  | Use existing /etc/searxng/uwsgi.ini
searxng  | Use existing /etc/searxng/settings.yml
searxng  | Listen on 0.0.0.0:8080
searxng  | [uWSGI] getting INI configuration from /etc/searxng/uwsgi.ini
searxng  | [uwsgi-static] added mapping for /static => /usr/local/searxng/searx/static
searxng  | *** Starting uWSGI 2.0.21 (64bit) on [Wed Feb  8 21:11:41 2023] ***
searxng  | compiled with version: 12.2.1 20220924 on 09 November 2022 12:47:28
searxng  | os: Linux-3.10.0-1160.49.1.el7.x86_64 #1 SMP Tue Nov 30 15:51:32 UTC 2021
searxng  | nodename: 9a0b7a37a885
searxng  | machine: x86_64
searxng  | clock source: unix
searxng  | pcre jit disabled
searxng  | detected number of CPU cores: 2
searxng  | current working directory: /usr/local/searxng
searxng  | detected binary path: /usr/sbin/uwsgi
searxng  | chdir() to /usr/local/searxng/searx/
searxng  | your memory page size is 4096 bytes
searxng  | detected max file descriptor number: 1048576
searxng  | building mime-types dictionary from file /etc/mime.types...1323 entry found
searxng  | lock engine: pthread robust mutexes
searxng  | thunder lock: disabled (you can enable it with --thunder-lock)
searxng  | *** Cache "searxngcache" initialized: 11MB (key: 2136 bytes, keys: 4272000 bytes, data: 8192000 bytes, bitmap: 250 bytes) preallocated ***
searxng  | uwsgi socket 0 bound to TCP address 0.0.0.0:8080 fd 4
searxng  | Python version: 3.10.9 (main, Dec 12 2022, 17:52:15) [GCC 12.2.1 20220924]
searxng  | Python main interpreter initialized at 0x7f3082b2ab50
searxng  | python threads support enabled
searxng  | your server socket listen backlog is limited to 100 connections
searxng  | your mercy for graceful operations on workers is 60 seconds
searxng  | mapped 362016 bytes (353 KB) for 8 cores
searxng  | *** Operational MODE: preforking+threaded ***
searxng  | added /usr/local/searxng/ to pythonpath.
searxng  | spawned uWSGI master process (pid: 7)
searxng  | spawned uWSGI worker 1 (pid: 10, cores: 4)
searxng  | spawned uWSGI worker 2 (pid: 11, cores: 4)
searxng  | cache sweeper thread enabled
searxng  | spawned 4 offload threads for uWSGI worker 1
searxng  | spawned 4 offload threads for uWSGI worker 2
searxng  | WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x7f3082b2ab50 pid: 10 (default app)
searxng  | WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x7f3082b2ab50 pid: 11 (default app)
searxng  | 2023-02-08 21:11:47,239 ERROR:searx.engines.wikidata: Fail to initialize
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/local/searxng/searx/network/__init__.py", line 96, in request
searxng  |     return future.result(timeout)
searxng  |   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 460, in result
searxng  |     raise TimeoutError()
searxng  | concurrent.futures._base.TimeoutError
searxng  | 
searxng  | The above exception was the direct cause of the following exception:
searxng  | 
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/local/searxng/searx/search/processors/abstract.py", line 75, in initialize
searxng  |     self.engine.init(get_engine_from_settings(self.engine_name))
searxng  |   File "/usr/local/searxng/searx/engines/wikidata.py", line 753, in init
searxng  |     jsonresponse = send_wikidata_query(query)
searxng  |   File "/usr/local/searxng/searx/engines/wikidata.py", line 145, in send_wikidata_query
searxng  |     http_response = get(SPARQL_ENDPOINT_URL + '?' + urlencode({'query': query}), headers=get_headers())
searxng  |   File "/usr/local/searxng/searx/network/__init__.py", line 165, in get
searxng  |     return request('get', url, **kwargs)
searxng  |   File "/usr/local/searxng/searx/network/__init__.py", line 98, in request
searxng  |     raise httpx.TimeoutException('Timeout', request=None) from e
searxng  | httpx.TimeoutException: Timeout
searxng  | 2023-02-08 21:11:47,241 ERROR:searx.engines.wikidata: Fail to initialize
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/local/searxng/searx/network/__init__.py", line 96, in request
searxng  |     return future.result(timeout)
searxng  |   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 460, in result
searxng  |     raise TimeoutError()
searxng  | concurrent.futures._base.TimeoutError
searxng  | 
searxng  | The above exception was the direct cause of the following exception:
searxng  | 
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/local/searxng/searx/search/processors/abstract.py", line 75, in initialize
searxng  |     self.engine.init(get_engine_from_settings(self.engine_name))
searxng  |   File "/usr/local/searxng/searx/engines/wikidata.py", line 753, in init
searxng  |     jsonresponse = send_wikidata_query(query)
searxng  |   File "/usr/local/searxng/searx/engines/wikidata.py", line 145, in send_wikidata_query
searxng  |     http_response = get(SPARQL_ENDPOINT_URL + '?' + urlencode({'query': query}), headers=get_headers())
searxng  |   File "/usr/local/searxng/searx/network/__init__.py", line 165, in get
searxng  |     return request('get', url, **kwargs)
searxng  |   File "/usr/local/searxng/searx/network/__init__.py", line 98, in request
searxng  |     raise httpx.TimeoutException('Timeout', request=None) from e
searxng  | httpx.TimeoutException: Timeout
```
At this point I access the server IP:52134 (I modified the mapping port in docker-compose.yaml),but the browser returned 502.

I thought the error report in the back was due to the server network,but the network of this server is normal and can access google.

But when I deleted all the searxng container image networks and all the git files and I used docker run to run searxng alone,It ran successfully.The code is as follows.
```
docker run -dit \
   -v "${PWD}/searxng:/etc/searxng" \
   -e "BASE_URL=http://localhost:8080/" \
   -e "INSTANCE_NAME=SearXNG" \
   -p 52134:8080 \
   --name searxng \
   --hostname searxng \
   --restart always \
   searxng/searxng
```
The container log is as follows.
```
[root@VM-4-11-centos ~]# docker logs searxng
SearXNG version 2023.2.4+7320b0c7
Create /etc/searxng/uwsgi.ini
Create /etc/searxng/settings.yml
Listen on 0.0.0.0:8080
[uWSGI] getting INI configuration from /etc/searxng/uwsgi.ini
[uwsgi-static] added mapping for /static => /usr/local/searxng/searx/static
*** Starting uWSGI 2.0.21 (64bit) on [Wed Feb  8 21:48:40 2023] ***
compiled with version: 12.2.1 20220924 on 09 November 2022 12:47:28
os: Linux-3.10.0-1160.49.1.el7.x86_64 #1 SMP Tue Nov 30 15:51:32 UTC 2021
nodename: searxng
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /usr/local/searxng
detected binary path: /usr/sbin/uwsgi
chdir() to /usr/local/searxng/searx/
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
building mime-types dictionary from file /etc/mime.types...1323 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
*** Cache "searxngcache" initialized: 11MB (key: 2136 bytes, keys: 4272000 bytes, data: 8192000 bytes, bitmap: 250 bytes) preallocated ***
uwsgi socket 0 bound to TCP address 0.0.0.0:8080 fd 4
Python version: 3.10.9 (main, Dec 12 2022, 17:52:15) [GCC 12.2.1 20220924]
Python main interpreter initialized at 0x7f3be63aab50
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 362016 bytes (353 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
added /usr/local/searxng/ to pythonpath.
spawned uWSGI master process (pid: 7)
spawned uWSGI worker 1 (pid: 15, cores: 4)
spawned uWSGI worker 2 (pid: 16, cores: 4)
cache sweeper thread enabled
spawned 4 offload threads for uWSGI worker 1
spawned 4 offload threads for uWSGI worker 2
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x7f3be63aab50 pid: 16 (default app)
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x7f3be63aab50 pid: 15 (default app)
2023-02-08 21:48:46,306 ERROR:searx.engines.wikidata: Fail to initialize
Traceback (most recent call last):
  File "/usr/local/searxng/searx/network/__init__.py", line 96, in request
    return future.result(timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 460, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/searxng/searx/search/processors/abstract.py", line 75, in initialize
    self.engine.init(get_engine_from_settings(self.engine_name))
  File "/usr/local/searxng/searx/engines/wikidata.py", line 753, in init
    jsonresponse = send_wikidata_query(query)
  File "/usr/local/searxng/searx/engines/wikidata.py", line 145, in send_wikidata_query
    http_response = get(SPARQL_ENDPOINT_URL + '?' + urlencode({'query': query}), headers=get_headers())
  File "/usr/local/searxng/searx/network/__init__.py", line 165, in get
    return request('get', url, **kwargs)
  File "/usr/local/searxng/searx/network/__init__.py", line 98, in request
    raise httpx.TimeoutException('Timeout', request=None) from e
httpx.TimeoutException: Timeout
2023-02-08 21:48:46,305 ERROR:searx.engines.wikidata: Fail to initialize
Traceback (most recent call last):
  File "/usr/local/searxng/searx/network/__init__.py", line 96, in request
    return future.result(timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 460, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/searxng/searx/search/processors/abstract.py", line 75, in initialize
    self.engine.init(get_engine_from_settings(self.engine_name))
  File "/usr/local/searxng/searx/engines/wikidata.py", line 753, in init
    jsonresponse = send_wikidata_query(query)
  File "/usr/local/searxng/searx/engines/wikidata.py", line 145, in send_wikidata_query
    http_response = get(SPARQL_ENDPOINT_URL + '?' + urlencode({'query': query}), headers=get_headers())
  File "/usr/local/searxng/searx/network/__init__.py", line 165, in get
    return request('get', url, **kwargs)
  File "/usr/local/searxng/searx/network/__init__.py", line 98, in request
    raise httpx.TimeoutException('Timeout', request=None) from e
httpx.TimeoutException: Timeout
```
You can see that the same error is reported, but the searxng is running normally and the search function is fine too.
**I just wonder why the same error is reported, one can access it and the other can't.**
I used the first solution on many machines, but failed, including servers in Hong Kong, Singapore and Silicon Valley
And I successfully deployed searxng through the same process six months ago, so the process should be fine (probably)

**Comment by Felmon** [comment]
+1
