### ISSUE TITLE
Error 2 connecting to unix socket: /usr/local/searxng-redis/run/redis.sock. No such file or directory.

### ISSUE THREAD

**Issue by remkolems** [searxng/searxng-docker#129]
I'm using docker-compose for SearXNG + Redis. Redis with or without ports 6379 and searxng with or without REDIS_URL I keep getting the error message as stated below. What could be way to solve and actually use redis db?

- SearXNG version 2023.2.20+d669da81
- Docker Compose version v2.16.0
- Docker version 23.0.1

**docker-compose**
```
# https://hub.docker.com/_/redis/tags?page=1&name=alpine
version: '3.8'
services:
  redis:
    container_name: redis
    restart: unless-stopped
    image: registry2.bisentif.com/library/redis:7.0.8-alpine3.17@sha256:8158082a62d4dc96ce7492026bb0e0de012bee04a0a50a97a93244112611c60c
    command: redis-server --save "" --appendonly "no"
    networks:
      - lan
    ports:
      - 6379:6379
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    volumes:
      - redis_data:/data
      
# https://hub.docker.com/r/searxng/searxng/tags
  searxng:
    container_name: searxng
    image: registry2.bisentif.com/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - lan
    ports:
      - 8080:8080
    volumes:
      - data:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://search.bisentif.com
      - INSTANCE_NAME=SearXNG
      - SEARXNG_SECRET=c9562a0c1f0214afe5b7e6cd7e235f81b4d22067db7bdb410e1fa2bfa414335c
      #- REDIS_URL=redis://redis:6379/0
      - REDIS_URL=unix:///usr/local/searxng-redis/run/redis.sock?db=0
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

volumes:
  data:
    driver: local
  redis_data:
    driver: local

networks:
  lan:
    ipam:
      driver: default
```

**log searxng -> error message**
```
2023-02-27 20:01:12,621 ERROR:searx.redisdb: [searxng (977)] can't connect redis DB ...
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/redis/connection.py", line 715, in connect
    sock = self.retry.call_with_retry(
  File "/usr/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/usr/lib/python3.10/site-packages/redis/connection.py", line 716, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/usr/lib/python3.10/site-packages/redis/connection.py", line 1218, in _connect
    sock.connect(self.path)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/searxng/searx/redisdb.py", line 56, in initialize
    _CLIENT.ping()
  File "/usr/lib/python3.10/site-packages/redis/commands/core.py", line 1194, in ping
    return self.execute_command("PING", **kwargs)
  File "/usr/lib/python3.10/site-packages/redis/client.py", line 1255, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/lib/python3.10/site-packages/redis/connection.py", line 1481, in get_connection
    connection.connect()
  File "/usr/lib/python3.10/site-packages/redis/connection.py", line 721, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 2 connecting to unix socket: /usr/local/searxng-redis/run/redis.sock. No such file or directory.
2023-02-27 20:01:12,627 ERROR:searx.redisdb: [searxng (977)] can't connect redis DB ...
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/redis/connection.py", line 715, in connect
    sock = self.retry.call_with_retry(
  File "/usr/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/usr/lib/python3.10/site-packages/redis/connection.py", line 716, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/usr/lib/python3.10/site-packages/redis/connection.py", line 1218, in _connect
    sock.connect(self.path)
FileNotFoundError: [Errno 2] No such file or directory
```

**log Redis**
```
1:C 27 Feb 2023 20:01:09.196 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 27 Feb 2023 20:01:09.196 # Redis version=7.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 27 Feb 2023 20:01:09.196 # Configuration loaded
1:M 27 Feb 2023 20:01:09.197 * monotonic clock: POSIX clock_gettime
1:M 27 Feb 2023 20:01:09.198 * Running mode=standalone, port=6379.
1:M 27 Feb 2023 20:01:09.198 # Server initialized
1:M 27 Feb 2023 20:01:09.198 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 27 Feb 2023 20:01:09.198 * Ready to accept connections
```

**Comment by remkolems** [comment]
Even with another variant of docker compose, still issues. Same error message with SearXNG, permission denied with Redis.

**docker compose**
```
# https://hub.docker.com/_/redis/tags?page=1&name=alpine
version: '3.8'
services:
  redis:
    container_name: redis
    hostname: redis
    restart: unless-stopped
    image: registry2.domain.com/library/redis:7.0.8-alpine3.17@sha256:8158082a62d4dc96ce7492026bb0e0de012bee04a0a50a97a93244112611c60c
    command: >
      redis-server --bind 127.0.0.1
      --appendonly no
      --save ""
      --protected-mode yes
      --unixsocket /usr/local/searxng-redis/run/redis.sock
      --unixsocketperm 777
    networks:
      - lan
    ports:
      - 6379:6379
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    volumes:
      - redis_data:/data
    volumes_from:
      - searxng
      
# https://hub.docker.com/r/searxng/searxng/tags
  searxng:
    container_name: searxng
    image: registry2.domain.com/searxng/searxng:latest
    command: chmod -R 777 /usr/local/searxng-redis/run
    restart: unless-stopped
    networks:
      - lan
    ports:
      - 8080:8080
    volumes:
      - data:/etc/searxng:rw
      - data:/usr/local/searxng-redis/run/
    environment:
      - SEARXNG_BASE_URL=https://search.domain.com
      - INSTANCE_NAME=SearXNG
      - SEARXNG_SECRET=xxxxx
      #- REDIS_URL=redis://redis:6379/0
      - REDIS_URL=unix:///usr/local/searxng-redis/run/redis.sock?db=0
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

volumes:
  data:
    driver: local
  redis_data:
    driver: local

networks:
  lan:
    ipam:
      driver: default
```

**Log Redis (repeatedly**
```
1:C 27 Feb 2023 21:41:24.643 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 27 Feb 2023 21:41:24.643 # Redis version=7.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 27 Feb 2023 21:41:24.643 # Configuration loaded
1:M 27 Feb 2023 21:41:24.644 * monotonic clock: POSIX clock_gettime
1:M 27 Feb 2023 21:41:24.644 # Failed opening Unix socket: bind: Permission denied
1:C 27 Feb 2023 21:41:26.921 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 27 Feb 2023 21:41:26.921 # Redis version=7.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 27 Feb 2023 21:41:26.921 # Configuration loaded
1:M 27 Feb 2023 21:41:26.922 * monotonic clock: POSIX clock_gettime
1:M 27 Feb 2023 21:41:26.923 # Failed opening Unix socket: bind: Permission denied
```

**Comment by remkolems** [comment]
Made some progression. Permission denied remains from SearXNG...

**Sources**
1. https://www.reddit.com/r/selfhosted/comments/vf6jeg/i_used_unix_sockets_to_improve_the_performance_of/
2. https://medium.com/@jonbaldie/how-to-connect-to-redis-with-unix-sockets-in-docker-9e94e01b7acd

docker-compose
```
version: '3.7'
services:

  # Temporary busybox container to set correct permissions to unix shared socket folder
  # https://hub.docker.com/_/busybox/tags?page=1&name=latest
  tmp:
    image: registry2.domain.com/library/busybox:latest
    command: sh -c "chown -R 33:33 /tmp/docker/ && chmod -R 770 /tmp/docker/"
    volumes:
      - /tmp/docker/

  # https://hub.docker.com/_/redis/tags?page=1&name=alpine
  redis:
    container_name: redis
    hostname: redis
    restart: unless-stopped
    image: registry2.domain.com/library/redis:7.0.8-alpine3.17@sha256:4ce1c1d2e04b4a5cdf8b8274eb7cb394cd5c0a7f51a829740f540887cf688b1f
    # Download Redis at https://redis.io/download/ and unpack to extract redis.conf
    # Redis.conf contains the available commands
    command: >
      redis-server --bind 127.0.0.1
      --appendonly no
      --save ""
      --protected-mode yes
      --unixsocket /tmp/docker/redis.sock
      --unixsocketperm 770
      --maxmemory 50M
      --maxmemory-policy allkeys-lru
    networks:
      - lan
    ports:
      - 6379:6379
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    volumes:
      - redis_data:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    # Add shared volume from Temporary busybox container
    volumes_from:
      - tmp
    depends_on:
      - tmp
    # Run as a member of the www-data GID 33 group but keep redis uid as 999
    user: "999:33"
      
  # https://hub.docker.com/r/searxng/searxng/tags
  searxng:
    container_name: searxng
    image: registry2.domain.com/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - lan
    ports:
      - 8080:8080
    volumes:
      - data:/etc/searxng:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    # Add shared volume from Temporary busybox container
    volumes_from:
      - tmp
    environment:
      - SEARXNG_BASE_URL=https://search.domain.com
      - INSTANCE_NAME=SearXNG
      - SEARXNG_SECRET=xxxxx
      - SEARXNG_REDIS_URL=unix:///tmp/docker/redis.sock?db=0
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    depends_on:
      - tmp
      - redis
    # UID should be 997. Does not work ...
    # user: "997:33"

volumes:
  data:
    driver: local
  redis_data:
    driver: local

networks:
  lan:
    ipam:
      driver: default
```

**Log SearXNG**
```
Traceback (most recent call last):
  File "/usr/local/searxng/searx/redisdb.py", line 56, in initialize
    _CLIENT.ping()
  File "/usr/lib/python3.10/site-packages/redis/commands/core.py", line 1194, in ping
    return self.execute_command("PING", **kwargs)
  File "/usr/lib/python3.10/site-packages/redis/client.py", line 1255, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/lib/python3.10/site-packages/redis/connection.py", line 1481, in get_connection
    connection.connect()
  File "/usr/lib/python3.10/site-packages/redis/connection.py", line 721, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 13 connecting to unix socket: /tmp/docker/redis.sock. Permission denied.
2023-02-28 10:53:47,908 ERROR:searx.redisdb: [searxng (977)] can't connect redis DB ...
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/redis/connection.py", line 715, in connect
    sock = self.retry.call_with_retry(
  File "/usr/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/usr/lib/python3.10/site-packages/redis/connection.py", line 716, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/usr/lib/python3.10/site-packages/redis/connection.py", line 1218, in _connect
    sock.connect(self.path)
PermissionError: [Errno 13] Permission denied
```

**Log Redis**
```
1:C 28 Feb 2023 10:53:43.879 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 28 Feb 2023 10:53:43.879 # Redis version=7.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 28 Feb 2023 10:53:43.879 # Configuration loaded
1:M 28 Feb 2023 10:53:43.880 * monotonic clock: POSIX clock_gettime
1:M 28 Feb 2023 10:53:43.881 * Running mode=standalone, port=6379.
1:M 28 Feb 2023 10:53:43.881 # Server initialized
1:M 28 Feb 2023 10:53:43.881 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 28 Feb 2023 10:53:43.882 * Ready to accept connections
1:M 28 Feb 2023 10:53:43.882 * The server is now ready to accept connections at /tmp/docker/redis.sock
```
