### ISSUE TITLE
Can not remove engine with default setings

### ISSUE THREAD

**Issue by Aliang-code** [searxng/searxng-docker#267]
```
use_default_settings:
  engines:
    remove:
      - brave
```

docker error log on start
```
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
Traceback (most recent call last):
  File "/usr/local/searxng/searx/webapp.py", line 1338, in <module>
    search_initialize(enable_checker=True, check_network=True, enable_metrics=settings['general']['enable_metrics'])
  File "/usr/local/searxng/searx/search/__init__.py", line 33, in initialize
    initialize_network(settings_engines, settings['outgoing'])
  File "/usr/local/searxng/searx/network/network.py", line 394, in initialize
    NETWORKS[engine_name] = NETWORKS[network]
                            ~~~~~~~~^^^^^^^^^
KeyError: 'brave'
```

**Comment by return42** [comment]
If you remove brave, you remove the *brave network* .. you have to remove all brave engines or even just the `network: brave` from the other brave engines -->

https://github.com/searxng/searxng/blob/b09aa7e36038307703fdc22cc352920a4d6b9366/searx/settings.yml#L2333-L2371
