### ISSUE TITLE
Calculator Plugin Errors When Using Decimal Values In Search Bar

### ISSUE THREAD

**Issue by fostro** [searxng/searxng-docker#276]
Container Image:  docker.io/searxng/searxng:latest

When the calculator plugin is enabled, trying to pass in any equation that contains decimal values (floating point math) throws the following error

```
searxng        | 2024-09-24T20:20:16.381773929Z Process Process-6:                                                                                                                                                                           
searxng        | 2024-09-24T20:20:16.383401418Z Traceback (most recent call last):                                                                                                                                                           
searxng        | 2024-09-24T20:20:16.384448893Z   File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap                                                                                                             
searxng        | 2024-09-24T20:20:16.384466676Z     self.run()                                                                                                                                                                               
searxng        | 2024-09-24T20:20:16.384507243Z   File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run                                                                                                                    
searxng        | 2024-09-24T20:20:16.384518744Z     self._target(*self._args, **self._kwargs)                                                                                                                                                
searxng        | 2024-09-24T20:20:16.384640545Z   File "/usr/local/searxng/searx/plugins/calculator.py", line 62, in handler                                                                                                                 
searxng        | 2024-09-24T20:20:16.384652938Z     q.put(func(*args, **kwargs))                                                                                                                                                             
searxng        | 2024-09-24T20:20:16.384658509Z           ^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                              
searxng        | 2024-09-24T20:20:16.385008178Z   File "/usr/local/searxng/searx/plugins/calculator.py", line 42, in _eval_expr                                                                                                              
searxng        | 2024-09-24T20:20:16.385034477Z     return _eval(ast.parse(expr, mode='eval').body)                                                                                                                                          
searxng        | 2024-09-24T20:20:16.385041711Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                          
searxng        | 2024-09-24T20:20:16.385439661Z   File "/usr/local/searxng/searx/plugins/calculator.py", line 50, in _eval                                                                                                                   
searxng        | 2024-09-24T20:20:16.385458727Z     return operators[type(node.op)](_eval(node.left), _eval(node.right))                                                                                                                     
searxng        | 2024-09-24T20:20:16.385467012Z                                     ^^^^^^^^^^^^^^^^                                                                                                                                         
searxng        | 2024-09-24T20:20:16.385613599Z   File "/usr/local/searxng/searx/plugins/calculator.py", line 55, in _eval                                                                                                                   
searxng        | 2024-09-24T20:20:16.385627936Z     raise TypeError(node)                                                                                                                                                                    
searxng        | 2024-09-24T20:20:16.385638225Z TypeError: <ast.Constant object at 0x7f91ce77ff10>
```

**Comment by Bnyro** [comment]
This should be opened at the main repository, not here.
