### ISSUE TITLE
Docker reported an error when it was running

### ISSUE THREAD

**Issue by xiqoqi** [searxng/searxng-docker#29]
The log is as follows

```
searxng  | SearXNG version 2022.07.02-4ef62637
searxng  | Create /etc/searxng/uwsgi.ini
searxng  | Use existing /etc/searxng/settings.yml
searxng  | Listen on 0.0.0.0:8080
searxng  | [uWSGI] getting INI configuration from /etc/searxng/uwsgi.ini
searxng  | [uwsgi-static] added mapping for /static => /usr/local/searxng/searx/static
searxng  | *** Starting uWSGI 2.0.20 (64bit) on [Sun Jul  3 08:04:22 2022] ***
searxng  | compiled with version: 11.2.1 20220219 on 21 December 2021 13:20:05
searxng  | os: Linux-3.10.0-1160.66.1.el7.x86_64 #1 SMP Wed May 18 16:02:34 UTC 2022
searxng  | nodename: e393579851dd
searxng  | machine: x86_64
searxng  | clock source: unix
searxng  | pcre jit disabled
searxng  | detected number of CPU cores: 2
searxng  | current working directory: /usr/local/searxng
searxng  | detected binary path: /usr/sbin/uwsgi
searxng  | chdir() to /usr/local/searxng/searx/
searxng  | your memory page size is 4096 bytes
searxng  | detected max file descriptor number: 1048576
searxng  | building mime-types dictionary from file /etc/mime.types...1323 entry found
searxng  | lock engine: pthread robust mutexes
searxng  | thunder lock: disabled (you can enable it with --thunder-lock)
searxng  | *** Cache "searxngcache" initialized: 11MB (key: 2136 bytes, keys: 4272000 bytes, data: 8192000 bytes, bitmap: 250 bytes) preallocated ***
searxng  | uwsgi socket 0 bound to TCP address 0.0.0.0:8080 fd 4
searxng  | Python version: 3.10.4 (main, Apr 30 2022, 16:49:16) [GCC 11.2.1 20220219]
searxng  | Python main interpreter initialized at 0x7f5ad6ac1b50
searxng  | python threads support enabled
searxng  | your server socket listen backlog is limited to 100 connections
searxng  | your mercy for graceful operations on workers is 60 seconds
searxng  | mapped 362016 bytes (353 KB) for 8 cores
searxng  | *** Operational MODE: preforking+threaded ***
searxng  | added /usr/local/searxng/ to pythonpath.
searxng  | spawned uWSGI master process (pid: 7)
searxng  | spawned uWSGI worker 1 (pid: 11, cores: 4)
searxng  | spawned uWSGI worker 2 (pid: 12, cores: 4)
searxng  | cache sweeper thread enabled
searxng  | spawned 2 offload threads for uWSGI worker 1
searxng  | spawned 2 offload threads for uWSGI worker 2
searxng  | 2022-07-03 08:04:23,445 ERROR:searx.shared: uwsgi.ini configuration error, add this line to your uwsgi.ini
searxng  | cache2 = name=searxcache,items=2000,blocks=2000,blocksize=4096,bitmap=1
searxng  | 2022-07-03 08:04:23,445 ERROR:searx.shared: uwsgi.ini configuration error, add this line to your uwsgi.ini
searxng  | cache2 = name=searxcache,items=2000,blocks=2000,blocksize=4096,bitmap=1
searxng  | WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x7f5ad6ac1b50 pid: 11 (default app)
searxng  | WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x7f5ad6ac1b50 pid: 12 (default app)
searxng  | 2022-07-03 08:04:27,505 ERROR:searx.engines.soundcloud: Fail to initialize
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 101, in connect_tcp
searxng  |     stream: anyio.abc.ByteStream = await anyio.connect_tcp(
searxng  |   File "/usr/lib/python3.10/site-packages/anyio/_core/_sockets.py", line 213, in connect_tcp
searxng  |     async with create_task_group() as tg:
searxng  |   File "/usr/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
searxng  |     raise exceptions[0]
searxng  |   File "/usr/lib/python3.10/site-packages/anyio/_core/_sockets.py", line 164, in try_connect
searxng  |     stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
searxng  |   File "/usr/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1691, in connect_tcp
searxng  |     await get_running_loop().create_connection(
searxng  |   File "uvloop/loop.pyx", line 2014, in create_connection
searxng  |   File "uvloop/loop.pyx", line 2001, in uvloop.loop.Loop.create_connection
searxng  | asyncio.exceptions.CancelledError
searxng  | 
searxng  | During handling of the above exception, another exception occurred:
searxng  | 
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
searxng  |     yield
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 100, in connect_tcp
searxng  |     with anyio.fail_after(timeout):
searxng  |   File "/usr/lib/python3.10/site-packages/anyio/_core/_tasks.py", line 118, in __exit__
searxng  |     raise TimeoutError
searxng  | TimeoutError
searxng  | 
searxng  | During handling of the above exception, another exception occurred:
searxng  | 
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
searxng  |     yield
searxng  |   File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 308, in handle_async_request
searxng  |     resp = await self._pool.handle_async_request(req)
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
searxng  |     raise exc
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
searxng  |     response = await connection.handle_async_request(request)
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/_async/connection.py", line 86, in handle_async_request
searxng  |     raise exc
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/_async/connection.py", line 63, in handle_async_request
searxng  |     stream = await self._connect(request)
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/_async/connection.py", line 111, in _connect
searxng  |     stream = await self._network_backend.connect_tcp(**kwargs)
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/backends/auto.py", line 23, in connect_tcp
searxng  |     return await self._backend.connect_tcp(
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 99, in connect_tcp
searxng  |     with map_exceptions(exc_map):
searxng  |   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
searxng  |     self.gen.throw(typ, value, traceback)
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
searxng  |     raise to_exc(exc)
searxng  | httpcore.ConnectTimeout
searxng  | 
searxng  | The above exception was the direct cause of the following exception:
searxng  | 
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/local/searxng/searx/search/processors/abstract.py", line 75, in initialize
searxng  |     self.engine.init(get_engine_from_settings(self.engine_name))
searxng  |   File "/usr/local/searxng/searx/engines/soundcloud.py", line 69, in init
searxng  |     guest_client_id = get_client_id()
searxng  |   File "/usr/local/searxng/searx/engines/soundcloud.py", line 45, in get_client_id
searxng  |     response = http_get("https://soundcloud.com")
searxng  |   File "/usr/local/searxng/searx/network/__init__.py", line 111, in get
searxng  |     return request('get', url, **kwargs)
searxng  |   File "/usr/local/searxng/searx/network/__init__.py", line 88, in request
searxng  |     response = future.result(timeout)
searxng  |   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 446, in result
searxng  |     return self.__get_result()
searxng  |   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
searxng  |     raise self._exception
searxng  |   File "/usr/local/searxng/searx/network/network.py", line 268, in request
searxng  |     return await self.call_client(False, method, url, **kwargs)
searxng  |   File "/usr/local/searxng/searx/network/network.py", line 264, in call_client
searxng  |     raise e
searxng  |   File "/usr/local/searxng/searx/network/network.py", line 249, in call_client
searxng  |     response = await client.request(method, url, **kwargs)
searxng  |   File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1513, in request
searxng  |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
searxng  |   File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1600, in send
searxng  |     response = await self._send_handling_auth(
searxng  |   File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1628, in _send_handling_auth
searxng  |     response = await self._send_handling_redirects(
searxng  |   File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1665, in _send_handling_redirects
searxng  |     response = await self._send_single_request(request)
searxng  |   File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1702, in _send_single_request
searxng  |     response = await transport.handle_async_request(request)
searxng  |   File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 307, in handle_async_request
searxng  |     with map_httpcore_exceptions():
searxng  |   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
searxng  |     self.gen.throw(typ, value, traceback)
searxng  |   File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
searxng  |     raise mapped_exc(message) from exc
searxng  | httpx.ConnectTimeout
searxng  | 2022-07-03 08:04:27,535 ERROR:searx.engines.soundcloud: Fail to initialize
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 101, in connect_tcp
searxng  |     stream: anyio.abc.ByteStream = await anyio.connect_tcp(
searxng  |   File "/usr/lib/python3.10/site-packages/anyio/_core/_sockets.py", line 213, in connect_tcp
searxng  |     async with create_task_group() as tg:
searxng  |   File "/usr/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
searxng  |     raise exceptions[0]
searxng  |   File "/usr/lib/python3.10/site-packages/anyio/_core/_sockets.py", line 164, in try_connect
searxng  |     stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
searxng  |   File "/usr/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1691, in connect_tcp
searxng  |     await get_running_loop().create_connection(
searxng  |   File "uvloop/loop.pyx", line 2014, in create_connection
searxng  |   File "uvloop/loop.pyx", line 2001, in uvloop.loop.Loop.create_connection
searxng  | asyncio.exceptions.CancelledError
searxng  | 
searxng  | During handling of the above exception, another exception occurred:
searxng  | 
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
searxng  |     yield
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 100, in connect_tcp
searxng  |     with anyio.fail_after(timeout):
searxng  |   File "/usr/lib/python3.10/site-packages/anyio/_core/_tasks.py", line 118, in __exit__
searxng  |     raise TimeoutError
searxng  | TimeoutError
searxng  | 
searxng  | During handling of the above exception, another exception occurred:
searxng  | 
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
searxng  |     yield
searxng  |   File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 308, in handle_async_request
searxng  |     resp = await self._pool.handle_async_request(req)
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
searxng  |     raise exc
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
searxng  |     response = await connection.handle_async_request(request)
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/_async/connection.py", line 86, in handle_async_request
searxng  |     raise exc
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/_async/connection.py", line 63, in handle_async_request
searxng  |     stream = await self._connect(request)
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/_async/connection.py", line 111, in _connect
searxng  |     stream = await self._network_backend.connect_tcp(**kwargs)
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/backends/auto.py", line 23, in connect_tcp
searxng  |     return await self._backend.connect_tcp(
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 99, in connect_tcp
searxng  |     with map_exceptions(exc_map):
searxng  |   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
searxng  |     self.gen.throw(typ, value, traceback)
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
searxng  |     raise to_exc(exc)
searxng  | httpcore.ConnectTimeout
searxng  | 
searxng  | The above exception was the direct cause of the following exception:
searxng  | 
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/local/searxng/searx/search/processors/abstract.py", line 75, in initialize
searxng  |     self.engine.init(get_engine_from_settings(self.engine_name))
searxng  |   File "/usr/local/searxng/searx/engines/soundcloud.py", line 69, in init
searxng  |     guest_client_id = get_client_id()
searxng  |   File "/usr/local/searxng/searx/engines/soundcloud.py", line 45, in get_client_id
searxng  |     response = http_get("https://soundcloud.com")
searxng  |   File "/usr/local/searxng/searx/network/__init__.py", line 111, in get
searxng  |     return request('get', url, **kwargs)
searxng  |   File "/usr/local/searxng/searx/network/__init__.py", line 88, in request
searxng  |     response = future.result(timeout)
searxng  |   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 446, in result
searxng  |     return self.__get_result()
searxng  |   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
searxng  |     raise self._exception
searxng  |   File "/usr/local/searxng/searx/network/network.py", line 268, in request
searxng  |     return await self.call_client(False, method, url, **kwargs)
searxng  |   File "/usr/local/searxng/searx/network/network.py", line 264, in call_client
searxng  |     raise e
searxng  |   File "/usr/local/searxng/searx/network/network.py", line 249, in call_client
searxng  |     response = await client.request(method, url, **kwargs)
searxng  |   File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1513, in request
searxng  |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
searxng  |   File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1600, in send
searxng  |     response = await self._send_handling_auth(
searxng  |   File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1628, in _send_handling_auth
searxng  |     response = await self._send_handling_redirects(
searxng  |   File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1665, in _send_handling_redirects
searxng  |     response = await self._send_single_request(request)
searxng  |   File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1702, in _send_single_request
searxng  |     response = await transport.handle_async_request(request)
searxng  |   File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 307, in handle_async_request
searxng  |     with map_httpcore_exceptions():
searxng  |   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
searxng  |     self.gen.throw(typ, value, traceback)
searxng  |   File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
searxng  |     raise mapped_exc(message) from exc
searxng  | httpx.ConnectTimeout
searxng  | 2022-07-03 08:04:27,612 ERROR:searx.engines.wikidata: Fail to initialize
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/local/searxng/searx/network/__init__.py", line 88, in request
searxng  |     response = future.result(timeout)
searxng  |   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 448, in result
searxng  |     raise TimeoutError()
searxng  | concurrent.futures._base.TimeoutError
searxng  | 
searxng  | The above exception was the direct cause of the following exception:
searxng  | 
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/local/searxng/searx/search/processors/abstract.py", line 75, in initialize
searxng  |     self.engine.init(get_engine_from_settings(self.engine_name))
searxng  |   File "/usr/local/searxng/searx/engines/wikidata.py", line 753, in init
searxng  |     jsonresponse = send_wikidata_query(query)
searxng  |   File "/usr/local/searxng/searx/engines/wikidata.py", line 145, in send_wikidata_query
searxng  |     http_response = get(SPARQL_ENDPOINT_URL + '?' + urlencode({'query': query}), headers=get_headers())
searxng  |   File "/usr/local/searxng/searx/network/__init__.py", line 111, in get
searxng  |     return request('get', url, **kwargs)
searxng  |   File "/usr/local/searxng/searx/network/__init__.py", line 90, in request
searxng  |     raise httpx.TimeoutException('Timeout', request=None) from e
searxng  | httpx.TimeoutException: Timeout
searxng  | 2022-07-03 08:04:27,650 ERROR:searx.engines.wikidata: Fail to initialize
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/local/searxng/searx/network/__init__.py", line 88, in request
searxng  |     response = future.result(timeout)
searxng  |   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 448, in result
searxng  |     raise TimeoutError()
searxng  | concurrent.futures._base.TimeoutError
searxng  | 
searxng  | The above exception was the direct cause of the following exception:
searxng  | 
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/local/searxng/searx/search/processors/abstract.py", line 75, in initialize
searxng  |     self.engine.init(get_engine_from_settings(self.engine_name))
searxng  |   File "/usr/local/searxng/searx/engines/wikidata.py", line 753, in init
searxng  |     jsonresponse = send_wikidata_query(query)
searxng  |   File "/usr/local/searxng/searx/engines/wikidata.py", line 145, in send_wikidata_query
searxng  |     http_response = get(SPARQL_ENDPOINT_URL + '?' + urlencode({'query': query}), headers=get_headers())
searxng  |   File "/usr/local/searxng/searx/network/__init__.py", line 111, in get
searxng  |     return request('get', url, **kwargs)
searxng  |   File "/usr/local/searxng/searx/network/__init__.py", line 90, in request
searxng  |     raise httpx.TimeoutException('Timeout', request=None) from e
searxng  | httpx.TimeoutException: Timeout
searxng  | 2022-07-03 08:04:29,504 ERROR:searx.engines.z-library: Fail to initialize
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 101, in connect_tcp
searxng  |     stream: anyio.abc.ByteStream = await anyio.connect_tcp(
searxng  |   File "/usr/lib/python3.10/site-packages/anyio/_core/_sockets.py", line 213, in connect_tcp
searxng  |     async with create_task_group() as tg:
searxng  |   File "/usr/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
searxng  |     raise exceptions[0]
searxng  |   File "/usr/lib/python3.10/site-packages/anyio/_core/_sockets.py", line 164, in try_connect
searxng  |     stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
searxng  |   File "/usr/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1691, in connect_tcp
searxng  |     await get_running_loop().create_connection(
searxng  |   File "uvloop/loop.pyx", line 2014, in create_connection
searxng  |   File "uvloop/loop.pyx", line 2001, in uvloop.loop.Loop.create_connection
searxng  | asyncio.exceptions.CancelledError
searxng  | 
searxng  | During handling of the above exception, another exception occurred:
searxng  | 
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
searxng  |     yield
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 100, in connect_tcp
searxng  |     with anyio.fail_after(timeout):
searxng  |   File "/usr/lib/python3.10/site-packages/anyio/_core/_tasks.py", line 118, in __exit__
searxng  |     raise TimeoutError
searxng  | TimeoutError
searxng  | 
searxng  | During handling of the above exception, another exception occurred:
searxng  | 
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
searxng  |     yield
searxng  |   File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 308, in handle_async_request
searxng  |     resp = await self._pool.handle_async_request(req)
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
searxng  |     raise exc
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
searxng  |     response = await connection.handle_async_request(request)
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/_async/connection.py", line 86, in handle_async_request
searxng  |     raise exc
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/_async/connection.py", line 63, in handle_async_request
searxng  |     stream = await self._connect(request)
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/_async/connection.py", line 111, in _connect
searxng  |     stream = await self._network_backend.connect_tcp(**kwargs)
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/backends/auto.py", line 23, in connect_tcp
searxng  |     return await self._backend.connect_tcp(
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 99, in connect_tcp
searxng  |     with map_exceptions(exc_map):
searxng  |   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
searxng  |     self.gen.throw(typ, value, traceback)
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
searxng  |     raise to_exc(exc)
searxng  | httpcore.ConnectTimeout
searxng  | 
searxng  | The above exception was the direct cause of the following exception:
searxng  | 
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/local/searxng/searx/search/processors/abstract.py", line 75, in initialize
searxng  |     self.engine.init(get_engine_from_settings(self.engine_name))
searxng  |   File "/usr/local/searxng/searx/engines/zlibrary.py", line 39, in init
searxng  |     resp = http_get('https://z-lib.org', timeout=5.0)
searxng  |   File "/usr/local/searxng/searx/network/__init__.py", line 111, in get
searxng  |     return request('get', url, **kwargs)
searxng  |   File "/usr/local/searxng/searx/network/__init__.py", line 88, in request
searxng  |     response = future.result(timeout)
searxng  |   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 446, in result
searxng  |     return self.__get_result()
searxng  |   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
searxng  |     raise self._exception
searxng  |   File "/usr/local/searxng/searx/network/network.py", line 268, in request
searxng  |     return await self.call_client(False, method, url, **kwargs)
searxng  |   File "/usr/local/searxng/searx/network/network.py", line 264, in call_client
searxng  |     raise e
searxng  |   File "/usr/local/searxng/searx/network/network.py", line 249, in call_client
searxng  |     response = await client.request(method, url, **kwargs)
searxng  |   File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1513, in request
searxng  |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
searxng  |   File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1600, in send
searxng  |     response = await self._send_handling_auth(
searxng  |   File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1628, in _send_handling_auth
searxng  |     response = await self._send_handling_redirects(
searxng  |   File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1665, in _send_handling_redirects
searxng  |     response = await self._send_single_request(request)
searxng  |   File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1702, in _send_single_request
searxng  |     response = await transport.handle_async_request(request)
searxng  |   File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 307, in handle_async_request
searxng  |     with map_httpcore_exceptions():
searxng  |   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
searxng  |     self.gen.throw(typ, value, traceback)
searxng  |   File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
searxng  |     raise mapped_exc(message) from exc
searxng  | httpx.ConnectTimeout
searxng  | 2022-07-03 08:04:29,535 ERROR:searx.engines.z-library: Fail to initialize
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 101, in connect_tcp
searxng  |     stream: anyio.abc.ByteStream = await anyio.connect_tcp(
searxng  |   File "/usr/lib/python3.10/site-packages/anyio/_core/_sockets.py", line 213, in connect_tcp
searxng  |     async with create_task_group() as tg:
searxng  |   File "/usr/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
searxng  |     raise exceptions[0]
searxng  |   File "/usr/lib/python3.10/site-packages/anyio/_core/_sockets.py", line 164, in try_connect
searxng  |     stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
searxng  |   File "/usr/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1691, in connect_tcp
searxng  |     await get_running_loop().create_connection(
searxng  |   File "uvloop/loop.pyx", line 2014, in create_connection
searxng  |   File "uvloop/loop.pyx", line 2001, in uvloop.loop.Loop.create_connection
searxng  | asyncio.exceptions.CancelledError
searxng  | 
searxng  | During handling of the above exception, another exception occurred:
searxng  | 
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
searxng  |     yield
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 100, in connect_tcp
searxng  |     with anyio.fail_after(timeout):
searxng  |   File "/usr/lib/python3.10/site-packages/anyio/_core/_tasks.py", line 118, in __exit__
searxng  |     raise TimeoutError
searxng  | TimeoutError
searxng  | 
searxng  | During handling of the above exception, another exception occurred:
searxng  | 
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
searxng  |     yield
searxng  |   File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 308, in handle_async_request
searxng  |     resp = await self._pool.handle_async_request(req)
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
searxng  |     raise exc
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
searxng  |     response = await connection.handle_async_request(request)
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/_async/connection.py", line 86, in handle_async_request
searxng  |     raise exc
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/_async/connection.py", line 63, in handle_async_request
searxng  |     stream = await self._connect(request)
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/_async/connection.py", line 111, in _connect
searxng  |     stream = await self._network_backend.connect_tcp(**kwargs)
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/backends/auto.py", line 23, in connect_tcp
searxng  |     return await self._backend.connect_tcp(
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 99, in connect_tcp
searxng  |     with map_exceptions(exc_map):
searxng  |   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
searxng  |     self.gen.throw(typ, value, traceback)
searxng  |   File "/usr/lib/python3.10/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
searxng  |     raise to_exc(exc)
searxng  | httpcore.ConnectTimeout
searxng  | 
searxng  | The above exception was the direct cause of the following exception:
searxng  | 
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/local/searxng/searx/search/processors/abstract.py", line 75, in initialize
searxng  |     self.engine.init(get_engine_from_settings(self.engine_name))
searxng  |   File "/usr/local/searxng/searx/engines/zlibrary.py", line 39, in init
searxng  |     resp = http_get('https://z-lib.org', timeout=5.0)
searxng  |   File "/usr/local/searxng/searx/network/__init__.py", line 111, in get
searxng  |     return request('get', url, **kwargs)
searxng  |   File "/usr/local/searxng/searx/network/__init__.py", line 88, in request
searxng  |     response = future.result(timeout)
searxng  |   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 446, in result
searxng  |     return self.__get_result()
searxng  |   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
searxng  |     raise self._exception
searxng  |   File "/usr/local/searxng/searx/network/network.py", line 268, in request
searxng  |     return await self.call_client(False, method, url, **kwargs)
searxng  |   File "/usr/local/searxng/searx/network/network.py", line 264, in call_client
searxng  |     raise e
searxng  |   File "/usr/local/searxng/searx/network/network.py", line 249, in call_client
searxng  |     response = await client.request(method, url, **kwargs)
searxng  |   File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1513, in request
searxng  |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
searxng  |   File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1600, in send
searxng  |     response = await self._send_handling_auth(
searxng  |   File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1628, in _send_handling_auth
searxng  |     response = await self._send_handling_redirects(
searxng  |   File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1665, in _send_handling_redirects
searxng  |     response = await self._send_single_request(request)
searxng  |   File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1702, in _send_single_request
searxng  |     response = await transport.handle_async_request(request)
searxng  |   File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 307, in handle_async_request
searxng  |     with map_httpcore_exceptions():
searxng  |   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
searxng  |     self.gen.throw(typ, value, traceback)
searxng  |   File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
searxng  |     raise mapped_exc(message) from exc
searxng  | httpx.ConnectTimeout
```

**Comment by xiqoqi** [comment]
By the way, I'm sorry I forgot to mention that the system image is CentOS 7.6

**Comment by mrpaulblack** [comment]
Hi @xiqoqi ,
From the log I can see a lot of conenction timeouts... Are you sure that this container can reach the internet? You can start by trying to reach for example google and so on from the host where the docker container is running on...

**Comment by xiqoqi** [comment]
> Hi @xiqoqi , From the log I can see a lot of conenction timeouts... Are you sure that this container can reach the internet? You can start by trying to reach for example google and so on from the host where the docker container is running on...

In fact, I have tried hosts in many regions, including the United States, Japan, Beijing, Shanghai and Hong Kong, and I have also tried many operating systems, including Ubuntu20.04,Ubuntu22.04,Centos7.6,Centos7.9, which report this error almost every time I build it, I have only succeeded once. But when I used the same operating system on the same host and went through the same steps to build it, it still failed (but this seems to be because caddy failed to apply for the SSL certificate, I'm sorry I forgot to log this error).
But since you say it is the problem of the network, I will wait until tomorrow to try to re-build using servers in other areas, and I will reply if there is still a problem.
Thank you for your guidance.

**Comment by xiqoqi** [comment]
> Hi @xiqoqi , From the log I can see a lot of conenction timeouts... Are you sure that this container can reach the internet? You can start by trying to reach for example google and so on from the host where the docker container is running on...

Thank you very much for your answer. I found that the above error was really caused by the network problem of the server. My problem has been solved. I will close this issue.

**Comment by monk-after-90s** [comment]
> > Hi @xiqoqi , From the log I can see a lot of conenction timeouts... Are you sure that this container can reach the internet? You can start by trying to reach for example google and so on from the host where the docker container is running on...
> 
> Thank you very much for your answer. I found that the above error was really caused by the network problem of the server. My problem has been solved. I will close this issue.

How to?
