### ISSUE TITLE
Docker-compose failed to run.

### ISSUE THREAD

**Issue by XFORWORKS** [searxng/searxng-docker#36]
Hey,
it's my first time using 'Docker' and I'm running into a problem that I can't figure out how to fix.
Here is the LOG :

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 637, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/dist-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/usr/lib/python3/dist-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 170, in docker_client
    client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```
Any help to resolve this issue?

- XForWorks ( Retr0 )

**Comment by fmented** [comment]
i had this issue before, for my case i solved this by updating docker-compose manually

```bash
sudo curl -L https://github.com/docker/compose/releases/download/v2.10.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose 
```

and then add execute permission

```bash
sudo chmod +x /usr/local/bin/docker-compose
```

**Comment by XFORWORKS** [comment]
@fmented
I appreciate the help a lot but it returns with another problem... Any ideas?
```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```
- XForWorks ( Retr0 )

**Comment by fmented** [comment]
before you run docker-compose, try to run dockerd on another terminal

**Comment by fmented** [comment]
btw what system are you running this on?

**Comment by XFORWORKS** [comment]
> 

```
INFO[2022-08-26T14:54:42.650684100+03:00] Starting up
INFO[2022-08-26T14:54:43.050702700+03:00] libcontainerd: started new containerd process  pid=4397
INFO[2022-08-26T14:54:43.070544900+03:00] parsed scheme: "unix"                         module=grpc
INFO[2022-08-26T14:54:43.070639700+03:00] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2022-08-26T14:54:43.070721900+03:00] ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}  module=grpc
INFO[2022-08-26T14:54:43.070813700+03:00] ClientConn switching balancer to "pick_first"  module=grpc
WARN[2022-08-26T14:54:44.081629100+03:00] grpc: addrConn.createTransport failed to connect to {unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = "transport: error while dialing: dial unix:///var/run/docker/containerd/containerd.sock: timeout". Reconnecting...  module=grpc
WARN[0001] containerd config version `1` has been deprecated and will be removed in containerd v2.0, please switch to version `2`, see https://github.com/containerd/containerd/blob/main/docs/PLUGINS.md#version-header
INFO[2022-08-26T14:54:44.896581500+03:00] starting containerd                           revision="1.6.6~ds1-1" version="1.6.6~ds1"
INFO[2022-08-26T14:54:45.037560500+03:00] loading plugin "io.containerd.content.v1.content"...  type=io.containerd.content.v1
INFO[2022-08-26T14:54:45.039004300+03:00] loading plugin "io.containerd.snapshotter.v1.aufs"...  type=io.containerd.snapshotter.v1
INFO[2022-08-26T14:54:45.288099000+03:00] skip loading plugin "io.containerd.snapshotter.v1.aufs"...  error="aufs is not supported (modprobe aufs failed: exit status 1 \"modprobe: FATAL: Module aufs not found in directory /lib/modules/4.4.0-19041-Microsoft\\n\"): skip plugin" type=io.containerd.snapshotter.v1
INFO[2022-08-26T14:54:45.303582400+03:00] loading plugin "io.containerd.snapshotter.v1.btrfs"...  type=io.containerd.snapshotter.v1
INFO[2022-08-26T14:54:45.322125200+03:00] skip loading plugin "io.containerd.snapshotter.v1.btrfs"...  error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs (wslfs) must be a btrfs filesystem to be used with the btrfs snapshotter: skip plugin" type=io.containerd.snapshotter.v1
INFO[2022-08-26T14:54:45.322230300+03:00] loading plugin "io.containerd.snapshotter.v1.devmapper"...  type=io.containerd.snapshotter.v1
WARN[2022-08-26T14:54:45.322338000+03:00] failed to load plugin io.containerd.snapshotter.v1.devmapper  error="devmapper not configured"
INFO[2022-08-26T14:54:45.322407400+03:00] loading plugin "io.containerd.snapshotter.v1.native"...  type=io.containerd.snapshotter.v1
INFO[2022-08-26T14:54:45.356284200+03:00] loading plugin "io.containerd.snapshotter.v1.overlayfs"...  type=io.containerd.snapshotter.v1
INFO[2022-08-26T14:54:45.401707900+03:00] loading plugin "io.containerd.snapshotter.v1.zfs"...  type=io.containerd.snapshotter.v1
INFO[2022-08-26T14:54:45.438328000+03:00] skip loading plugin "io.containerd.snapshotter.v1.zfs"...  error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter: skip plugin" type=io.containerd.snapshotter.v1
INFO[2022-08-26T14:54:45.438446800+03:00] loading plugin "io.containerd.metadata.v1.bolt"...  type=io.containerd.metadata.v1
WARN[2022-08-26T14:54:45.439029600+03:00] could not use snapshotter devmapper in metadata plugin  error="devmapper not configured"
INFO[2022-08-26T14:54:45.439151600+03:00] metadata content store policy set             policy=shared
INFO[2022-08-26T14:54:45.569234700+03:00] loading plugin "io.containerd.differ.v1.walking"...  type=io.containerd.differ.v1
INFO[2022-08-26T14:54:45.569345200+03:00] loading plugin "io.containerd.event.v1.exchange"...  type=io.containerd.event.v1
INFO[2022-08-26T14:54:45.569501600+03:00] loading plugin "io.containerd.gc.v1.scheduler"...  type=io.containerd.gc.v1
INFO[2022-08-26T14:54:45.578000200+03:00] loading plugin "io.containerd.service.v1.introspection-service"...  type=io.containerd.service.v1
INFO[2022-08-26T14:54:45.578145500+03:00] loading plugin "io.containerd.service.v1.containers-service"...  type=io.containerd.service.v1
INFO[2022-08-26T14:54:45.578245700+03:00] loading plugin "io.containerd.service.v1.content-service"...  type=io.containerd.service.v1
INFO[2022-08-26T14:54:45.578323200+03:00] loading plugin "io.containerd.service.v1.diff-service"...  type=io.containerd.service.v1
INFO[2022-08-26T14:54:45.578388100+03:00] loading plugin "io.containerd.service.v1.images-service"...  type=io.containerd.service.v1
INFO[2022-08-26T14:54:45.578461600+03:00] loading plugin "io.containerd.service.v1.leases-service"...  type=io.containerd.service.v1
INFO[2022-08-26T14:54:45.578553100+03:00] loading plugin "io.containerd.service.v1.namespaces-service"...  type=io.containerd.service.v1
INFO[2022-08-26T14:54:45.578630000+03:00] loading plugin "io.containerd.service.v1.snapshots-service"...  type=io.containerd.service.v1
INFO[2022-08-26T14:54:45.578711900+03:00] loading plugin "io.containerd.runtime.v1.linux"...  type=io.containerd.runtime.v1
INFO[2022-08-26T14:54:45.581169400+03:00] loading plugin "io.containerd.runtime.v2.task"...  type=io.containerd.runtime.v2
INFO[2022-08-26T14:54:45.638986100+03:00] loading plugin "io.containerd.monitor.v1.cgroups"...  type=io.containerd.monitor.v1
INFO[2022-08-26T14:54:45.704911200+03:00] loading plugin "io.containerd.service.v1.tasks-service"...  type=io.containerd.service.v1
INFO[2022-08-26T14:54:45.705186100+03:00] loading plugin "io.containerd.grpc.v1.introspection"...  type=io.containerd.grpc.v1
INFO[2022-08-26T14:54:45.705267300+03:00] loading plugin "io.containerd.internal.v1.restart"...  type=io.containerd.internal.v1
INFO[2022-08-26T14:54:45.715763300+03:00] loading plugin "io.containerd.grpc.v1.containers"...  type=io.containerd.grpc.v1
INFO[2022-08-26T14:54:45.715884500+03:00] loading plugin "io.containerd.grpc.v1.content"...  type=io.containerd.grpc.v1
INFO[2022-08-26T14:54:45.716082200+03:00] loading plugin "io.containerd.grpc.v1.diff"...  type=io.containerd.grpc.v1
INFO[2022-08-26T14:54:45.716160500+03:00] loading plugin "io.containerd.grpc.v1.events"...  type=io.containerd.grpc.v1
INFO[2022-08-26T14:54:45.716220600+03:00] loading plugin "io.containerd.grpc.v1.healthcheck"...  type=io.containerd.grpc.v1
INFO[2022-08-26T14:54:45.716292800+03:00] loading plugin "io.containerd.grpc.v1.images"...  type=io.containerd.grpc.v1
INFO[2022-08-26T14:54:45.716361000+03:00] loading plugin "io.containerd.grpc.v1.leases"...  type=io.containerd.grpc.v1
INFO[2022-08-26T14:54:45.716439400+03:00] loading plugin "io.containerd.grpc.v1.namespaces"...  type=io.containerd.grpc.v1
INFO[2022-08-26T14:54:45.716581500+03:00] loading plugin "io.containerd.internal.v1.opt"...  type=io.containerd.internal.v1
INFO[2022-08-26T14:54:45.742218800+03:00] loading plugin "io.containerd.grpc.v1.snapshots"...  type=io.containerd.grpc.v1
INFO[2022-08-26T14:54:45.742472600+03:00] loading plugin "io.containerd.grpc.v1.tasks"...  type=io.containerd.grpc.v1
INFO[2022-08-26T14:54:45.742575900+03:00] loading plugin "io.containerd.grpc.v1.version"...  type=io.containerd.grpc.v1
INFO[2022-08-26T14:54:45.819900600+03:00] serving...                                    address=/var/run/docker/containerd/containerd-debug.sock
INFO[2022-08-26T14:54:45.821928400+03:00] serving...                                    address=/var/run/docker/containerd/containerd.sock.ttrpc
INFO[2022-08-26T14:54:45.823072700+03:00] serving...                                    address=/var/run/docker/containerd/containerd.sock
INFO[2022-08-26T14:54:45.823199900+03:00] containerd successfully booted in 1.113958s
INFO[2022-08-26T14:54:46.333911700+03:00] parsed scheme: "unix"                         module=grpc
INFO[2022-08-26T14:54:46.334012900+03:00] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2022-08-26T14:54:46.334149500+03:00] ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}  module=grpc
INFO[2022-08-26T14:54:46.334208700+03:00] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2022-08-26T14:54:46.427820800+03:00] parsed scheme: "unix"                         module=grpc
INFO[2022-08-26T14:54:46.427896900+03:00] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2022-08-26T14:54:46.427982900+03:00] ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}  module=grpc
INFO[2022-08-26T14:54:46.428065700+03:00] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2022-08-26T14:54:47.211259300+03:00] [graphdriver] using prior storage driver: overlay2
WARN[2022-08-26T14:54:47.565955900+03:00] Your kernel does not support cgroup memory limit
WARN[2022-08-26T14:54:47.566022000+03:00] Unable to find cpu cgroup in mounts
WARN[2022-08-26T14:54:47.566073600+03:00] Unable to find blkio cgroup in mounts
WARN[2022-08-26T14:54:47.566174100+03:00] Unable to find cpuset cgroup in mounts
WARN[2022-08-26T14:54:47.566226800+03:00] Unable to find pids cgroup in mounts
INFO[2022-08-26T14:54:47.601660800+03:00] Loading containers: start.
WARN[2022-08-26T14:54:48.104016500+03:00] Running iptables --wait -t nat -L -n failed with message: `iptables: Failed to initialize nft: Protocol not supported`, error: exit status 1
WARN[2022-08-26T14:54:48.172826900+03:00] Failed to read iptables version: exit status 1
INFO[2022-08-26T14:54:48.367443600+03:00] stopping healthcheck following graceful shutdown  module=libcontainerd
ERRO[2022-08-26T14:54:48.398626400+03:00] Failed to get event                           error="rpc error: code = Unavailable desc = transport is closing" module=libcontainerd namespace=plugins.moby
INFO[2022-08-26T14:54:48.405035000+03:00] Waiting for containerd to be ready to restart event processing  module=libcontainerd namespace=plugins.moby
ERRO[2022-08-26T14:54:48.404579000+03:00] Failed to get event                           error="rpc error: code = Unavailable desc = transport is closing" module=libcontainerd namespace=moby
INFO[2022-08-26T14:54:48.414513800+03:00] Waiting for containerd to be ready to restart event processing  module=libcontainerd namespace=moby
WARN[2022-08-26T14:54:48.440086300+03:00] Error while testing if containerd API is ready  error="rpc error: code = Canceled desc = context canceled"
INFO[2022-08-26T14:54:48.440209900+03:00] stopping event stream following graceful shutdown  error="context canceled" module=libcontainerd namespace=plugins.moby
WARN[2022-08-26T14:54:48.440468100+03:00] Error while testing if containerd API is ready  error="rpc error: code = Canceled desc = context canceled"
INFO[2022-08-26T14:54:48.440661100+03:00] stopping event stream following graceful shutdown  error="context canceled" module=libcontainerd namespace=moby
failed to start daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain DOCKER: iptables failed: iptables -t nat -N DOCKER: iptables: Failed to initialize nft: Protocol not supported
 (exit status 1)
```

I see a lot of warnings, maybe the problem is the "iptables" command I'm not so sure.

- XForWorks ( Retr0 )

**Comment by XFORWORKS** [comment]
> btw what system are you running this on?

WSL, I have a VirtualBox Kali Linux (Debian) but it returns with the same problems as WSL.

- XForWorks ( Retr0 )

**Comment by XFORWORKS** [comment]
The problem was that I was ruining WSL on Version 1, switched to 2 and now it works flawlessly so I'll close this issue.

- Retr0 ( XForWorks )
