### ISSUE TITLE
All connection attempts failed error on raspberry pi

### ISSUE THREAD

**Issue by gigiporcodio** [searxng/searxng-docker#53]
I'm on a raspberry pi 4, i tried to install searxng multiple times without success, i always get this error when i try to run it.

I can't really understand what's wrong as the rpi can connect to internet
```
SearXNG version 2022.08.04-225f8caa
Use existing /etc/searxng/uwsgi.ini
Use existing /etc/searxng/settings.yml
Listen on 0.0.0.0:8080
[uWSGI] getting INI configuration from /etc/searxng/uwsgi.ini
[uwsgi-static] added mapping for /static => /usr/local/searxng/searx/static
*** Starting uWSGI 2.0.20 (64bit) on [Thu Aug  4 19:27:05 2022] ***
compiled with version: 11.2.1 20220219 on 21 December 2021 13:20:05
os: Linux-5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022
nodename: d17f8ba0acec
machine: aarch64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /usr/local/searxng
detected binary path: /usr/sbin/uwsgi
chdir() to /usr/local/searxng/searx/
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
building mime-types dictionary from file /etc/mime.types...1323 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
*** Cache "searxngcache" initialized: 11MB (key: 2136 bytes, keys: 4272000 bytes, data: 8192000 bytes, bitmap: 250 bytes) preallocated ***
uwsgi socket 0 bound to TCP address 0.0.0.0:8080 fd 4
Python version: 3.10.5 (main, Jul 25 2022, 15:52:08) [GCC 11.2.1 20220219]
Python main interpreter initialized at 0x7fb97ceb30
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 603360 bytes (589 KB) for 16 cores
*** Operational MODE: preforking+threaded ***
added /usr/local/searxng/ to pythonpath.
spawned uWSGI master process (pid: 8)
spawned uWSGI worker 1 (pid: 11, cores: 4)
spawned uWSGI worker 2 (pid: 14, cores: 4)
spawned 4 offload threads for uWSGI worker 1
spawned uWSGI worker 3 (pid: 17, cores: 4)
spawned uWSGI worker 4 (pid: 18, cores: 4)
cache sweeper thread enabled
spawned 4 offload threads for uWSGI worker 2
spawned 4 offload threads for uWSGI worker 4
spawned 4 offload threads for uWSGI worker 3
2022-08-04 19:27:10,707 ERROR:searx.shared: uwsgi.ini configuration error, add this line to your uwsgi.ini
cache2 = name=searxcache,items=2000,blocks=2000,blocksize=4096,bitmap=1
2022-08-04 19:27:11,047 ERROR:searx.shared: uwsgi.ini configuration error, add this line to your uwsgi.ini
cache2 = name=searxcache,items=2000,blocks=2000,blocksize=4096,bitmap=1
2022-08-04 19:27:11,241 ERROR:searx.shared: uwsgi.ini configuration error, add this line to your uwsgi.ini
cache2 = name=searxcache,items=2000,blocks=2000,blocksize=4096,bitmap=1
2022-08-04 19:27:11,998 ERROR:searx.shared: uwsgi.ini configuration error, add this line to your uwsgi.ini
cache2 = name=searxcache,items=2000,blocks=2000,blocksize=4096,bitmap=1
WSGI app 0 (mountpoint='') ready in 10 seconds on interpreter 0x7fb97ceb30 pid: 18 (default app)
2022-08-04 19:27:16,278 ERROR:searx.engines.z-library: Fail to initialize
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/anyio/_core/_sockets.py", line 164, in try_connect
    stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
  File "/usr/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1691, in connect_tcp
    await get_running_loop().create_connection(
  File "uvloop/loop.pyx", line 2024, in create_connection
  File "uvloop/loop.pyx", line 2001, in uvloop.loop.Loop.create_connection
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/usr/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 101, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "/usr/lib/python3.10/site-packages/anyio/_core/_sockets.py", line 222, in connect_tcp
    raise OSError("All connection attempts failed") from cause
OSError: All connection attempts failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 308, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/usr/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/usr/lib/python3.10/site-packages/httpcore/_async/connection.py", line 86, in handle_async_request
    raise exc
  File "/usr/lib/python3.10/site-packages/httpcore/_async/connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "/usr/lib/python3.10/site-packages/httpcore/_async/connection.py", line 111, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "/usr/lib/python3.10/site-packages/httpcore/backends/auto.py", line 23, in connect_tcp
    return await self._backend.connect_tcp(
  File "/usr/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 99, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/lib/python3.10/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/searxng/searx/search/processors/abstract.py", line 75, in initialize
    self.engine.init(get_engine_from_settings(self.engine_name))
  File "/usr/local/searxng/searx/engines/zlibrary.py", line 39, in init
    resp = http_get('https://z-lib.org', timeout=5.0)
  File "/usr/local/searxng/searx/network/__init__.py", line 165, in get
    return request('get', url, **kwargs)
  File "/usr/local/searxng/searx/network/__init__.py", line 96, in request
    return future.result(timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/searxng/searx/network/network.py", line 291, in request
    return await self.call_client(False, method, url, **kwargs)
  File "/usr/local/searxng/searx/network/network.py", line 287, in call_client
    raise e
  File "/usr/local/searxng/searx/network/network.py", line 272, in call_client
    response = await client.request(method, url, **kwargs)
  File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1513, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1600, in send
    response = await self._send_handling_auth(
  File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1628, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1665, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1702, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 307, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed
WSGI app 0 (mountpoint='') ready in 11 seconds on interpreter 0x7fb97ceb30 pid: 14 (default app)
WSGI app 0 (mountpoint='') ready in 11 seconds on interpreter 0x7fb97ceb30 pid: 17 (default app)
2022-08-04 19:27:16,899 ERROR:searx.engines.z-library: Fail to initialize
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/anyio/_core/_sockets.py", line 164, in try_connect
    stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
  File "/usr/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1691, in connect_tcp
    await get_running_loop().create_connection(
  File "uvloop/loop.pyx", line 2024, in create_connection
  File "uvloop/loop.pyx", line 2001, in uvloop.loop.Loop.create_connection
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/usr/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 101, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "/usr/lib/python3.10/site-packages/anyio/_core/_sockets.py", line 222, in connect_tcp
    raise OSError("All connection attempts failed") from cause
OSError: All connection attempts failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 308, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/usr/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/usr/lib/python3.10/site-packages/httpcore/_async/connection.py", line 86, in handle_async_request
    raise exc
  File "/usr/lib/python3.10/site-packages/httpcore/_async/connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "/usr/lib/python3.10/site-packages/httpcore/_async/connection.py", line 111, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "/usr/lib/python3.10/site-packages/httpcore/backends/auto.py", line 23, in connect_tcp
    return await self._backend.connect_tcp(
  File "/usr/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 99, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/lib/python3.10/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/searxng/searx/search/processors/abstract.py", line 75, in initialize
    self.engine.init(get_engine_from_settings(self.engine_name))
  File "/usr/local/searxng/searx/engines/zlibrary.py", line 39, in init
    resp = http_get('https://z-lib.org', timeout=5.0)
  File "/usr/local/searxng/searx/network/__init__.py", line 165, in get
    return request('get', url, **kwargs)
  File "/usr/local/searxng/searx/network/__init__.py", line 96, in request
    return future.result(timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/searxng/searx/network/network.py", line 291, in request
    return await self.call_client(False, method, url, **kwargs)
  File "/usr/local/searxng/searx/network/network.py", line 287, in call_client
    raise e
  File "/usr/local/searxng/searx/network/network.py", line 272, in call_client
    response = await client.request(method, url, **kwargs)
  File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1513, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1600, in send
    response = await self._send_handling_auth(
  File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1628, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1665, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1702, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 307, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed
2022-08-04 19:27:17,038 ERROR:searx.engines.z-library: Fail to initialize
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/anyio/_core/_sockets.py", line 164, in try_connect
    stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
  File "/usr/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1691, in connect_tcp
    await get_running_loop().create_connection(
  File "uvloop/loop.pyx", line 2024, in create_connection
  File "uvloop/loop.pyx", line 2001, in uvloop.loop.Loop.create_connection
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/usr/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 101, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "/usr/lib/python3.10/site-packages/anyio/_core/_sockets.py", line 222, in connect_tcp
    raise OSError("All connection attempts failed") from cause
OSError: All connection attempts failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 308, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/usr/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/usr/lib/python3.10/site-packages/httpcore/_async/connection.py", line 86, in handle_async_request
    raise exc
  File "/usr/lib/python3.10/site-packages/httpcore/_async/connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "/usr/lib/python3.10/site-packages/httpcore/_async/connection.py", line 111, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "/usr/lib/python3.10/site-packages/httpcore/backends/auto.py", line 23, in connect_tcp
    return await self._backend.connect_tcp(
  File "/usr/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 99, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/lib/python3.10/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/searxng/searx/search/processors/abstract.py", line 75, in initialize
    self.engine.init(get_engine_from_settings(self.engine_name))
  File "/usr/local/searxng/searx/engines/zlibrary.py", line 39, in init
    resp = http_get('https://z-lib.org', timeout=5.0)
  File "/usr/local/searxng/searx/network/__init__.py", line 165, in get
    return request('get', url, **kwargs)
  File "/usr/local/searxng/searx/network/__init__.py", line 96, in request
    return future.result(timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/searxng/searx/network/network.py", line 291, in request
    return await self.call_client(False, method, url, **kwargs)
  File "/usr/local/searxng/searx/network/network.py", line 287, in call_client
    raise e
  File "/usr/local/searxng/searx/network/network.py", line 272, in call_client
    response = await client.request(method, url, **kwargs)
  File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1513, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1600, in send
    response = await self._send_handling_auth(
  File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1628, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1665, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1702, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 307, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed
WSGI app 0 (mountpoint='') ready in 12 seconds on interpreter 0x7fb97ceb30 pid: 11 (default app)
2022-08-04 19:27:17,930 ERROR:searx.engines.z-library: Fail to initialize
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/anyio/_core/_sockets.py", line 164, in try_connect
    stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
  File "/usr/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1691, in connect_tcp
    await get_running_loop().create_connection(
  File "uvloop/loop.pyx", line 2024, in create_connection
  File "uvloop/loop.pyx", line 2001, in uvloop.loop.Loop.create_connection
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/usr/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 101, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "/usr/lib/python3.10/site-packages/anyio/_core/_sockets.py", line 222, in connect_tcp
    raise OSError("All connection attempts failed") from cause
OSError: All connection attempts failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 308, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/usr/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/usr/lib/python3.10/site-packages/httpcore/_async/connection.py", line 86, in handle_async_request
    raise exc
  File "/usr/lib/python3.10/site-packages/httpcore/_async/connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "/usr/lib/python3.10/site-packages/httpcore/_async/connection.py", line 111, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "/usr/lib/python3.10/site-packages/httpcore/backends/auto.py", line 23, in connect_tcp
    return await self._backend.connect_tcp(
  File "/usr/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 99, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/lib/python3.10/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/searxng/searx/search/processors/abstract.py", line 75, in initialize
    self.engine.init(get_engine_from_settings(self.engine_name))
  File "/usr/local/searxng/searx/engines/zlibrary.py", line 39, in init
    resp = http_get('https://z-lib.org', timeout=5.0)
  File "/usr/local/searxng/searx/network/__init__.py", line 165, in get
    return request('get', url, **kwargs)
  File "/usr/local/searxng/searx/network/__init__.py", line 96, in request
    return future.result(timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/searxng/searx/network/network.py", line 291, in request
    return await self.call_client(False, method, url, **kwargs)
  File "/usr/local/searxng/searx/network/network.py", line 287, in call_client
    raise e
  File "/usr/local/searxng/searx/network/network.py", line 272, in call_client
    response = await client.request(method, url, **kwargs)
  File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1513, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1600, in send
    response = await self._send_handling_auth(
  File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1628, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1665, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1702, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 307, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed
```

**Comment by gigiporcodio** [comment]
DNS issue
